stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/processed
    - src/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/features
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/features
    - src/model_building.py
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    outs:
    - model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - model.pkl
    - src/model_evaluation.py
    metrics:
    - metrics.json
